# Introduction to NumPy: The Foundation for Efficient Array Operations

NumPy is a powerful Python package that serves as the fundamental building block for a wide range of scientific computing and data analysis tasks. Its name stands for "Numerical Python," reflecting its ability to efficiently handle numerical data.

At its core, NumPy provides a high-performance multidimensional array object, ndarray, which enables you to store and manipulate large amounts of homogeneous data efficiently. This array data structure is essential for many other popular Python packages used in data science and machine learning, such as pandas, scikit-learn, and TensorFlow.

One of the key advantages of NumPy lies in its efficient implementation. The underlying array operations are written in C, making them considerably faster than equivalent operations implemented in pure Python. This performance boost is crucial when dealing with large datasets, complex mathematical computations, or time-sensitive applications.

A central concept in NumPy is the ability to vectorize operations, which allows you to perform mathematical operations on entire arrays rather than iterating through each element individually. By leveraging this feature, you can write concise and expressive code, often eliminating the need for explicit loops. This not only simplifies the code but also significantly improves execution speed.

NumPy offers a comprehensive suite of functions for mathematical operations, random number generation, linear algebra, Fourier transformations, and more. Additionally, it provides tools for reading and writing array data to disk, enabling seamless integration with various file formats.

In this practical course, we will delve into the essential functionalities of NumPy, exploring its powerful array manipulation capabilities, mathematical functions, and data analysis techniques. By the end of the course, you will have a solid foundation in NumPy, allowing you to efficiently work with numerical data and pave the way for advanced data science tasks.

Let's embark on this exciting journey of scientific computing with NumPy!

*Generated with ChatGTPv3.5 May 24th Version, prompt: "Hi, buddy. I am helping with some practical courses in python using a Jupyter notebook in a summer school. I need to generate some introductory text about numpy, a python package. I want to remark that is the base for much other python packages, that is efficient because of its implementation and that allows to vectorize operations."*

In [1]:
# First of all, we need to load the package. BE SURE TO HAVE IT INSTALLED!
import numpy as np

<h2> Data types </h2>

NumPy, the numerical computing package for Python, offers a rich set of objects and data types that are essential for efficient array manipulation and scientific computing. Let's take a brief look at some of the key components:

1. **ndarray (N-dimensional Array):** The `ndarray` is the fundamental object in NumPy, providing a powerful data structure to represent homogeneous, multi-dimensional arrays. It enables efficient storage and manipulation of numerical data, supporting various mathematical and logical operations. With NumPy's ndarray, you can effortlessly handle large datasets and perform vectorized computations.

2. **Scalars:** NumPy introduces scalar data types that extend beyond Python's built-in types. These include integers (`int`), floating-point numbers (`float`), complex numbers (`complex`), and boolean values (`bool`). NumPy's scalars offer increased precision and optimized memory utilization compared to the standard Python equivalents.

3. **Data Type Objects (dtype):** NumPy introduces its own data type objects, allowing you to define the precise characteristics of elements within arrays. These dtype objects specify the size, byte order, and data format of the elements. By utilizing specific dtypes, you can ensure the desired level of precision and control over memory allocation.

4. **Structured Arrays:** NumPy provides the ability to create structured arrays, where each element can be a composite of multiple fields or attributes. This feature is particularly useful when working with structured data, such as CSV files, where elements may have different data types and sizes. Structured arrays enable efficient handling of heterogeneous data in a tabular format.

5. **Universal Functions (ufuncs):** NumPy's ufuncs are functions that operate element-wise on ndarrays, enabling efficient and fast mathematical operations. These functions are highly optimized and implemented in compiled C code, providing significant performance advantages over equivalent Python loops. Ufuncs cover a wide range of mathematical operations, including arithmetic, trigonometry, exponential functions, and more.

NumPy's rich collection of objects and data types forms the backbone of scientific computing in Python. By leveraging these powerful tools, you can efficiently work with arrays, perform complex calculations, handle structured data, and manipulate numerical data with ease.

*Generated with ChatGTPv3.5 May 24th Version, prompt: "Hi, buddy! Now I will like you to generate a short review of the objects and data types of numpy. Could you please format it for markdown?"*

### 1) ndarray (N-dimensional Array) and 2) Scalars 3) Data Type Objects (dtype)

#### 1D arrays

Similarly to a list, a 1D array is a sequence of elements. All elements in a numpy array are of the same data type. We can define the precision in bytes of the elements 

In [2]:
int_array_1 = np.array([3,4,5,6,7], np.int16)
print(int_array_1.dtype)

int16


In [3]:
int_array_2 = np.array([11,13,2,1], np.int32)
print(int_array_2.dtype)

int32


In [4]:
int_array_3 = np.array([11,13,2,1], np.int64)
print(int_array_3.dtype)

int64


In [5]:
my_int_array = np.array([3,4,5,6,7,8,9], np.uint8)
print(my_int_array.dtype)

uint8


Let's look into this data type:

- `int64` is a 64-bit signed integer, equivalent to the basic scalar type `int` in numpy (`dtype=int` in NumPy, it is equivalent to `dtype=np.int64`), allowing for larger integer values. It has a wider range, enabling the representation of integers from approximately -9 quintillion to +9 quintillion. It uses 8 bytes of memory per element.

There are other data types that you can use, such as `int32`:


- `int32` (in fact, the built-in `int` type in basic Python is equivalent to this dtype) is a 32-bit signed integer, capable of representing integers in the range from approximately -2 billion to +2 billion. It uses 4 bytes of memory per element.

The choice between `int32` and `int64` depends on the range of values you need to represent, with `int32` being suitable for smaller integers and `int64` necessary for larger ones or precise calculations.


*Modified from ChatGTPv3.5 May 24th Version, prompt: "Could you please give me a short explanation between int32 and int64 and between float32 and float64 data types? Could you please format it for markdown?"*

In [6]:
float_array_1 = np.array([2.3, 4.3, 1.3], dtype=np.float16)
print(float_array_1.dtype)

float16


In [7]:
float_array_2 = np.array([2.3, 4.3, 1.3], dtype=np.float32)
print(float_array_2.dtype)

float32


In [8]:
my_float_array = np.array([32.3,43.1,9])
print(my_float_array.dtype)

float64


`float16`, `float32` and `float64` are floating-point data types used to represent decimal numbers with fractional parts.

 - `float16` is a 16-bit floating-point number, utilizing 2 bytes of memory per element. It provides lower precision compared to `float32` and `float64`, with approximately 3-4 decimal digits of precision. `float16` is commonly used in scenarios where memory usage is critical, such as on resource-constrained devices or when dealing with large datasets.
 

 - `float32` (or `float` in Python) is a 32-bit floating-point number, utilizing 4 bytes of memory per element. It provides approximately 7 decimal digits of precision.
 
  
 - `float64` is a 64-bit floating-point number, utilizing 8 bytes of memory per element. It offers higher precision and can represent decimal numbers with approximately 15 decimal digits of precision.
  
The choice between `float32` and `float64` depends on the required precision of your calculations. `float64` is generally recommended for more accurate and precise calculations in scientific or financial applications, while `float32` suffices for many general-purpose applications, consuming less memory. When working with numerical data, it is crucial to select the appropriate data type based on the desired range and precision of the values to ensure accurate computations while managing memory efficiently.

*Modified from ChatGTPv3.5 May 24th Version, prompt: "Could you please give me a short explanation between int32 and int64 and between float32 and float64 data types? Could you please format it for markdown?"*

<h4> Indexing and slicing </h4>
To access elements inside a numpy array we use indexing:

In [9]:
print(my_int_array)
print(my_int_array[0])
print(my_int_array[2])
print(my_int_array[-1])
print(my_int_array[-3])

[3 4 5 6 7 8 9]
3
5
9
7


To access multiple elements at a time we use slicing:

In [10]:
print(my_int_array)
print(my_int_array[2:4])
print(my_int_array[1:5])
print(my_int_array[:4])
print(my_int_array[2:])
print(my_int_array[-3:])

[3 4 5 6 7 8 9]
[5 6]
[4 5 6 7]
[3 4 5 6]
[5 6 7 8 9]
[7 8 9]


We can redefine an element in an array by selecting its index and assigning it to a new value:

In [11]:
new_array = np.array([3,4,5,6,7,8,9], np.float32)
print(new_array)
new_array[3] = 11
print('modify 4th element')
print(new_array)

[3. 4. 5. 6. 7. 8. 9.]
modify 4th element
[ 3.  4.  5. 11.  7.  8.  9.]


Similarly, with multiple indices:

In [12]:
new_array[-3:] = [12,13,14]
new_array = np.delete(new_array, 4)
print(new_array)

[ 3.  4.  5. 11. 13. 14.]


# Introduction to NumPy: The Foundation for Efficient Array Operations

NumPy is a powerful Python package that serves as the fundamental building block for a wide range of scientific computing and data analysis tasks. Its name stands for "Numerical Python," reflecting its ability to efficiently handle numerical data.

At its core, NumPy provides a high-performance multidimensional array object, ndarray, which enables you to store and manipulate large amounts of homogeneous data efficiently. This array data structure is essential for many other popular Python packages used in data science and machine learning, such as pandas, scikit-learn, and TensorFlow.

One of the key advantages of NumPy lies in its efficient implementation. The underlying array operations are written in C, making them considerably faster than equivalent operations implemented in pure Python. This performance boost is crucial when dealing with large datasets, complex mathematical computations, or time-sensitive applications.

A central concept in NumPy is the ability to vectorize operations, which allows you to perform mathematical operations on entire arrays rather than iterating through each element individually. By leveraging this feature, you can write concise and expressive code, often eliminating the need for explicit loops. This not only simplifies the code but also significantly improves execution speed.

NumPy offers a comprehensive suite of functions for mathematical operations, random number generation, linear algebra, Fourier transformations, and more. Additionally, it provides tools for reading and writing array data to disk, enabling seamless integration with various file formats.

In this practical course, we will delve into the essential functionalities of NumPy, exploring its powerful array manipulation capabilities, mathematical functions, and data analysis techniques. By the end of the course, you will have a solid foundation in NumPy, allowing you to efficiently work with numerical data and pave the way for advanced data science tasks.

Let's embark on this exciting journey of scientific computing with NumPy!

*Generated with ChatGTPv3.5 May 24th Version, prompt: "Hi, buddy. I am helping with some practical courses in python using a Jupyter notebook in a summer school. I need to generate some introductory text about numpy, a python package. I want to remark that is the base for much other python packages, that is efficient because of its implementation and that allows to vectorize operations."*

<h4>Multi-dimensional arrays</h4>

In [13]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(my_matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


We use multiple indices to access elements of multidimensional arrays. In the case of a 2D matrix, the first index refers to the row index, while the second one is for the columns:

In [14]:
print(my_matrix[1,2])
print(my_matrix[-1,-1])

6
12


If we use only one index we can select entire rows:

In [15]:
print(my_matrix[0])
print(my_matrix[1:3])

[1 2 3]
[[4 5 6]
 [7 8 9]]


If we want to select an entire column:

In [16]:
print(my_matrix[:,2])

[ 3  6  9 12]


Similarly, for 3 dimensional arrays:

In [17]:
multidim_array = np.array([
    [[3,4,2],[5,4,4]],
    [[7,8,7],[6,6,6]]
])

Now our array consists of 2 2x3 matrices. This means that element at index 0 is the first 2x3 matrix, and element at index 1 is the second 2x3 matrix. We can then access the elements of the matrix as before:

In [18]:
multidim_array.shape

(2, 2, 3)

In [19]:
print(multidim_array)
print('')
print(multidim_array[0])
print(multidim_array[0].shape)
print('')
print(multidim_array[0,:,1])
print(multidim_array[1,-1])

[[[3 4 2]
  [5 4 4]]

 [[7 8 7]
  [6 6 6]]]

[[3 4 2]
 [5 4 4]]
(2, 3)

[4 4]
[6 6 6]


<h4>Dimensions</h4>

A convenient way to keep track of the operations that we perform is to check the dimension of input, intermediate or output arrays. Numpy provides an easy way to see the shape of an array:

In [20]:
my_matrix.shape

(4, 3)

In [21]:
multidim_array.shape

(2, 2, 3)

To look at the number of dimensions:

In [22]:
my_matrix.ndim

2

In [23]:
multidim_array.ndim

3

In [24]:
my_int_array.ndim

1

<h4>Zeros, ones, arange</h4>

With numpy we can easily create arrays of zeros, ones and evenly spaced values:

In [25]:
array_zeros = np.zeros(10)
print(array_zeros)
matrix_zeros = np.zeros((5,5))
matrix_zeros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
array_ones = np.ones(10)
print(array_ones)
matrix_ones = np.ones((5,5))
matrix_ones

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [29]:
np.arange(4,10,2)

array([4, 6, 8])

The third argument in `np.arange` is the step size.

<h4> Reshape </h4>

In [30]:
# We can define a 1-dimension array of low precision floats FROM 0 to 1.4 by 0.2 steps
unidim_array = np.arange(0, 1.6, 0.2, dtype='float16')
unidim_array

array([0.    , 0.2   , 0.4   , 0.5996, 0.8   , 1.    , 1.199 , 1.399 ],
      dtype=float16)

In [31]:
# 2D 8x1 array
np.reshape(unidim_array, (8,1))

array([[0.    ],
       [0.2   ],
       [0.4   ],
       [0.5996],
       [0.8   ],
       [1.    ],
       [1.199 ],
       [1.399 ]], dtype=float16)

In [32]:
# 2D 1x8 array
np.reshape(unidim_array, (1,8))

array([[0.    , 0.2   , 0.4   , 0.5996, 0.8   , 1.    , 1.199 , 1.399 ]],
      dtype=float16)

In [33]:
# 2D 2x4 array
np.reshape(unidim_array, (2,4))

array([[0.    , 0.2   , 0.4   , 0.5996],
       [0.8   , 1.    , 1.199 , 1.399 ]], dtype=float16)

In [34]:
# 2D 2x2x2 array
np.reshape(unidim_array, (2,2,2))

array([[[0.    , 0.2   ],
        [0.4   , 0.5996]],

       [[0.8   , 1.    ],
        [1.199 , 1.399 ]]], dtype=float16)

### 4) Structured arrays

In [35]:
# Define the data types for the structured array
dt = np.dtype([('name', np.str_, 20), ('age', np.int32), ('score', np.float64)])

# Create a structured array
data = np.array([('John', 25, 85.5), ('Alice', 30, 92.3), ('Bob', 28, 77.8)], dtype=dt)
print(data)

[('John', 25, 85.5) ('Alice', 30, 92.3) ('Bob', 28, 77.8)]


In [36]:
# Access and print specific fields of the structured array
print("Name:", data['name'])
print("Age:", data['age'])
print("Score:", data['score'])

Name: ['John' 'Alice' 'Bob']
Age: [25 30 28]
Score: [85.5 92.3 77.8]


This is very useful for complex datasets, although for that it is better to use the `pandas` package which is built upon `numpy` and for a more versatile manipulation of complex datasets.

<h3>5) Universal Functions (ufuncs)</h3>

#### a) Basic numpy functions

In [37]:
# Create a sample array
arr = np.array([23, 56, 12, 90, 45, 78, 34])

# Find the minimum value in the array
min_value = np.min(arr)
print("Minimum Value:", min_value)

# Find the maximum value in the array
max_value = np.max(arr)
print("Maximum Value:", max_value)

# Calculate the mean of the array
mean_value = np.mean(arr)
print("Mean:", mean_value)

# Calculate the standard deviation of the array
std_value = np.std(arr)
print("Standard Deviation:", std_value)

# Calculate the variance of the array
var_value = np.var(arr)
print("Variance:", var_value)

Minimum Value: 12
Maximum Value: 90
Mean: 48.285714285714285
Standard Deviation: 26.331481894787277
Variance: 693.3469387755102


In [38]:
np.max(my_matrix, axis=0)

array([10, 11, 12])

In [39]:
my_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
np.linalg.norm(my_matrix, axis=1)

array([ 3.74165739,  8.77496439, 13.92838828, 19.10497317])

#### b) Adding, Subtracting, Multiplying, and Dividing by a Number, using broadcasting

Broadcasting refers to how numpy treats arrays with different dimension during arithmetic operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes.

In [41]:
# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Add a number to each element
result_add = np.add(arr, 10)
print("Addition Result:", result_add)

# Subtract a number from each element
result_subtract = np.subtract(arr, 3)
print("Subtraction Result:", result_subtract)

# Multiply each element by a number
result_multiply = np.multiply(arr, 2)
print("Multiplication Result:", result_multiply)

# Divide each element by a number
result_divide = np.divide(arr, 2)
print("Division Result:", result_divide)

Addition Result: [11 12 13 14 15]
Subtraction Result: [-2 -1  0  1  2]
Multiplication Result: [ 2  4  6  8 10]
Division Result: [0.5 1.  1.5 2.  2.5]


#### c) Adding, Subtracting arrays

In [42]:
# Just sum them up
print(arr+arr)

# Same for sustraction
print(arr-arr)

[ 2  4  6  8 10]
[0 0 0 0 0]


In [43]:
my_new_matrix = np.arange(12).reshape(-1,3).astype(np.float64)

#### d) Multiplying Two Arrays

In [44]:
# Create a 2D 2x3 sample array
arr1 = np.array(np.reshape(np.arange(0,6,1), (2,3)))
print(np.shape(arr1))

# Create a 2D 3x2 sample array
arr2 = np.array(np.reshape(np.arange(0,6,1), (3,2)))
print(np.shape(arr2))

# Multiply them
print(np.matmul(arr1,arr2))

# Note that the opposite gives a matrix with a different shape
print(np.matmul(arr2,arr1))

(2, 3)
(3, 2)
[[10 13]
 [28 40]]
[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]


#### e) Multiplying and dividing two arrays ELEMENT-WISE

In [45]:
# Create two sample arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

# Multiply the arrays element-wise
result_multiply_arrays = np.multiply(arr1, arr2)
print("Element-wise Multiplication Result:", result_multiply_arrays)

# Divide the arrays element-wise
result_multiply_arrays = np.divide(arr1, arr2)
print("Element-wise Division Result:", result_multiply_arrays)

Element-wise Multiplication Result: [ 2  8 18 32 50]
Element-wise Division Result: [0.5 0.5 0.5 0.5 0.5]


#### f) Using apply_along_axis and Defining a Custom Function

In [46]:
# Define a custom function
def custom_function_average(row):
    return np.sum(row) / len(row)

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Apply the custom function along the rows (axis=1)
result_apply_along_axis = np.apply_along_axis(custom_function_average, axis=1, arr=arr_2d)
print("Apply along Axis Result:", result_apply_along_axis)

Apply along Axis Result: [2. 5. 8.]


<h4>Boolean arrays</h4>

Numpy arrays can also be booleans. We can use arrays as indices.

In [47]:
my_new_matrix = np.arange(12).reshape(4,-1).astype(np.float64)

In [48]:
my_new_matrix[my_new_matrix==0] = np.inf

In [49]:
# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Create a boolean mask based on a condition
mask = arr > 2

# Use the boolean mask to index the array
result = arr[mask]

# Print the result
print("Result:", result)

Result: [3 4 5]


<h4> Pandas </h4>

The two primary data structures in pandas as Series and Dataframes, which allow for efficient handling and manipulation of tabular data. Let's see how we can use pandas to load and treat data from a dataset of breast tumor cells.

In [71]:
import pandas as pd

breast_cancer = pd.read_csv('breast_cancer.csv')

In [72]:
breast_cancer

x.radius_mean  x.texture_mean  x.perimeter_mean  x.area_mean  \
0           13.540           14.36             87.46        566.3   
1           13.080           15.71             85.63        520.0   
2            9.504           12.44             60.34        273.9   
3           13.030           18.42             82.61        523.8   
4            8.196           16.84             51.71        201.9   
..             ...             ...               ...          ...   
564         20.920           25.09            143.00       1347.0   
565         21.560           22.39            142.00       1479.0   
566         20.130           28.25            131.20       1261.0   
567         16.600           28.08            108.30        858.1   
568         20.600           29.33            140.10       1265.0   

     x.smoothness_mean  x.compactness_mean  x.concavity_mean  \
0              0.09779             0.08129           0.06664   
1              0.10750             0.12700           0.04568   
2              0.10240             0.06492           0.02956   
3              0.08983             0.03766           0.02562   
4              0.08600             0.05943           0.01588   
..                 ...                 ...               ...   
564            0.10990             0.22360           0.31740   
565            0.11100             0.11590           0.24390   
566            0.09780             0.10340           0.14400   
567            0.08455             0.10230           0.09251   
568            0.11780             0.27700           0.35140   

     x.concave_pts_mean  x.symmetry_mean  x.fractal_dim_mean  ...  \
0              0.047810           0.1885             0.05766  ...   
1              0.031100           0.1967             0.06811  ...   
2              0.020760           0.1815             0.06905  ...   
3              0.029230           0.1467             0.05863  ...   
4              0.005917           0.1769             0.06503  ...   
..                  ...              ...                 ...  ...   
564            0.147400           0.2149             0.06879  ...   
565            0.138900           0.1726             0.05623  ...   
566            0.097910           0.1752             0.05533  ...   
567            0.053020           0.1590             0.05648  ...   
568            0.152000           0.2397             0.07016  ...   

     x.texture_worst  x.perimeter_worst  x.area_worst  x.smoothness_worst  \
0              19.26              99.70         711.2             0.14400   
1              20.49              96.09         630.5             0.13120   
2              15.66              65.13         314.9             0.13240   
3              22.81              84.46         545.9             0.09701   
4              21.96              57.26         242.2             0.12970   
..               ...                ...           ...                 ...   
564            29.41             179.10        1819.0             0.14070   
565            26.40             166.10        2027.0             0.14100   
566            38.25             155.00        1731.0             0.11660   
567            34.12             126.70        1124.0             0.11390   
568            39.42             184.60        1821.0             0.16500   

     x.compactness_worst  x.concavity_worst  x.concave_pts_worst  \
0                0.17730            0.23900              0.12880   
1                0.27760            0.18900              0.07283   
2                0.11480            0.08867              0.06227   
3                0.04619            0.04833              0.05013   
4                0.13570            0.06880              0.02564   
..                   ...                ...                  ...   
564              0.41860            0.65990              0.25420   
565              0.21130            0.41070              0.22160   
566              0.19220            0.321

Each row in the table is an observation, and each column is a characteristic. In our example, the columns are characteristics of cell nuclei in breast tumors. The last column represents the target. 'M' means that the observation corresponds to malignant tumor, while 'B' means that the tumor is benign.